/**
 * Frame extractor — hero MP4 (already generated by hero-video-generator.ts) →
 * JPG frame sequence for the ScrollSequenceHero canvas-scrub component.
 *
 * Zero extra generation cost: reuses the video the pipeline already produces
 * per lead. Recipe matches the one documented in root CLAUDE.md
 * (fps=7, scale=1280:-2, q:v 4 — ~50KB/frame, ~7-10MB total for a 5s clip).
 */
import { execFile } from 'node:child_process'
import { promisify } from 'node:util'
import { mkdtempSync, readdirSync, readFileSync, writeFileSync, rmSync } from 'node:fs'
import { join } from 'node:path'
import { tmpdir } from 'node:os'

const execFileAsync = promisify(execFile)

export interface ExtractedFrame {
  filename: string
  buffer: Buffer
}

export interface FrameExtractionResult {
  frames: ExtractedFrame[]
  totalBytes: number
}

const FRAME_SIZE_BUDGET_BYTES = 10 * 1024 * 1024

async function assertFfmpeg(): Promise<void> {
  try {
    await execFileAsync('ffmpeg', ['-version'])
  } catch {
    throw new Error('ffmpeg not found on PATH — install with: brew install ffmpeg')
  }
}

/**
 * Extract a JPG frame sequence from an MP4 buffer.
 * Frame filenames are `frame_0001.jpg`, `frame_0002.jpg`, ... (sorted, 1-indexed)
 * to match ScrollSequenceHero's default `framePath` convention.
 */
export async function extractFramesFromVideo(videoBuffer: Buffer): Promise<FrameExtractionResult> {
  await assertFfmpeg()

  const workDir = mkdtempSync(join(tmpdir(), 'scroll-hero-frames-'))
  const inputPath = join(workDir, 'input.mp4')
  writeFileSync(inputPath, videoBuffer)

  try {
    await execFileAsync('ffmpeg', [
      '-y', '-i', inputPath,
      '-vf', 'fps=7,scale=1280:-2',
      '-q:v', '4',
      join(workDir, 'frame_%04d.jpg'),
    ])

    const filenames = readdirSync(workDir)
      .filter((f) => /^frame_\d+\.jpg$/.test(f))
      .sort()

    const frames: ExtractedFrame[] = filenames.map((filename) => ({
      filename,
      buffer: readFileSync(join(workDir, filename)),
    }))

    const totalBytes = frames.reduce((sum, f) => sum + f.buffer.length, 0)
    if (totalBytes > FRAME_SIZE_BUDGET_BYTES) {
      console.warn(
        `[FrameExtractor] ${frames.length} frames = ${(totalBytes / 1024 / 1024).toFixed(1)}MB, ` +
        `over the ${FRAME_SIZE_BUDGET_BYTES / 1024 / 1024}MB budget — uploading anyway`,
      )
    }

    return { frames, totalBytes }
  } finally {
    rmSync(workDir, { recursive: true, force: true })
  }
}
